[package]
name = "wasp"
version = "0.1.0"
edition = "2021"

[dependencies]
monostate = "0.1.13"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
wasabi_leb128 = "0.4.0"
