use super::{
    error::ParseError, BlockType, FuncIdx, GlobalIdX, LabelIdX, LocalIdX, MemArg, Parsable,
    TableIdX, TypeIdX,
};
use crate::hex::Hex;
use std::io::Read;
use Instr::*;

#[derive(Debug, Clone)]
#[allow(non_camel_case_types, unused)]
#[repr(u8)]
pub enum Instr {
    block_start = 0xFF,
    x00_unreachable = 0x00,
    x02_block(BlockType, Vec<Instr>) = 0x02,
    x03_loop(BlockType, Vec<Instr>) = 0x03,
    x0c_br(LabelIdX) = 0x0c,
    x0d_br_if(LabelIdX) = 0x0d,
    x0e_br_table(Vec<LabelIdX>, LabelIdX) = 0x0e,
    x0f_return = 0x0f,
    x10_i32_const(i32) = 0x10,
    x11_call_indirect(TypeIdX, TableIdX) = 0x11,
    x1a_drop = 0x1a,
    x1b_select = 0x1b,
    x20_local_get(LocalIdX) = 0x20,
    x21_local_set(LocalIdX) = 0x21,
    x22_local_tee(LocalIdX) = 0x22,
    x23_global_get(GlobalIdX) = 0x23,
    x24_global_set(GlobalIdX) = 0x24,
    x26_table_set(TableIdX) = 0x26,
    x28_i32_load(MemArg) = 0x28,
    x29_i64_load(MemArg) = 0x29,
    x2c_i32_load8_s(MemArg) = 0x2c,
    x2d_i32_load8_u(MemArg) = 0x2d,
    x2f_i32_load16_u(MemArg) = 0x2f,
    x36_i32_store(MemArg) = 0x36,
    x37_i64_store(MemArg) = 0x37,
    x3a_i32_store8(MemArg) = 0x3a,
    x3b_i32_store16(MemArg) = 0x3b,
    x40_grow = 0x40,
    x41_call(FuncIdx) = 0x41,
    x42_i64_const(i64) = 0x42,
    x45_i32_eqz = 0x45,
    x46_i32_eq = 0x46,
    x47_i32_ne = 0x47,
    x48_lt_s = 0x48,
    x49_i32_lt_u = 0x49,
    x4a_i32_gt_s = 0x4a,
    x4b_i32_gt_u = 0x4b,
    x4c_i32_le_s = 0x4c,
    x4d_i32_le_u = 0x4d,
    x4e_i32_ge_s = 0x4e,
    x4f_i32_ge_u = 0x4f,
    x51_i64_eq = 0x51,
    x52_i64_ne = 0x52,
    x67_i32_clz = 0x67,
    x68_i32_ctz = 0x68,
    x6a_i32_add = 0x6a,
    x6b_i32_sub = 0x6b,
    x6c_i32_mul = 0x6c,
    x6e_i32_div_u = 0x6e,
    x71_i32_and = 0x71,
    x72_i32_or = 0x72,
    x73_i32_xor = 0x73,
    x74_i32_shl = 0x74,
    x76_i32_shr_u = 0x76,
    x77_i32_rotl = 0x77,
    x7c_i64_add = 0x7c,
    x7e_i64_mul = 0x7e,
    x84_i64_or = 0x84,
    x86_i64_shl = 0x86,
    x88_i64_shr_u = 0x88,
    xa7_i32_wrap_i64 = 0xa7,
    xad_i64_extend_i32_u = 0xad,
}
impl Parsable for Instr {
    fn parse_inner(
        data: &mut std::io::Cursor<&[u8]>,
        stack: super::DebugStack,
    ) -> Result<Self, super::error::ParseError>
    where
        Self: std::marker::Sized,
    {
        let mut typ = [0];
        data.read_exact(&mut typ)?;
        Ok(match typ[0] {
            0x00 => x00_unreachable,
            0x01 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x02 => {
                let block_type = Parsable::parse(data, stack)?;
                let mut v = Vec::new();
                loop {
                    match Instr::parse(data, stack) {
                        Ok(i) => v.push(i),
                        Err(ParseError::EndOfInstructions) => {
                            stack.pop();
                            break;
                        }
                        Err(e) => Err(e)?,
                    }
                }
                x02_block(block_type, v)
            }
            0x03 => {
                let block_type = Parsable::parse(data, stack)?;
                let mut v = Vec::new();
                loop {
                    match Instr::parse(data, stack) {
                        Ok(i) => v.push(i),
                        Err(ParseError::EndOfInstructions) => {
                            stack.pop();
                            break;
                        }
                        Err(e) => Err(e)?,
                    }
                }
                x03_loop(block_type, v)
            }
            0x04 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x05 => Err(ParseError::EndOfInstructions)?,
            0x06 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x07 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x08 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x09 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x0a => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x0b => Err(ParseError::EndOfInstructions)?,
            0x0c => x0c_br(Parsable::parse(data, stack)?),
            0x0d => x0d_br_if(Parsable::parse(data, stack)?),
            0x0e => x0e_br_table(Parsable::parse(data, stack)?, Parsable::parse(data, stack)?),
            0x0f => x0f_return,
            0x10 => x41_call(FuncIdx::parse(data, stack)?),
            0x11 => x11_call_indirect(Parsable::parse(data, stack)?, Parsable::parse(data, stack)?),
            0x12 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x13 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x14 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x15 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x16 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x17 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x18 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x19 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x1a => x1a_drop,
            0x1b => x1b_select,
            0x1c => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x1d => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x1e => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x1f => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x20 => x20_local_get(Parsable::parse(data, stack)?),
            0x21 => x21_local_set(Parsable::parse(data, stack)?),
            0x22 => x22_local_tee(Parsable::parse(data, stack)?),
            0x23 => x23_global_get(Parsable::parse(data, stack)?),
            0x24 => x24_global_set(Parsable::parse(data, stack)?),
            0x25 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x26 => x26_table_set(Parsable::parse(data, stack)?),
            0x27 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x28 => x28_i32_load(Parsable::parse(data, stack)?),
            0x29 => x29_i64_load(Parsable::parse(data, stack)?),
            0x2a => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x2b => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x2c => x2c_i32_load8_s(Parsable::parse(data, stack)?),
            0x2d => x2d_i32_load8_u(Parsable::parse(data, stack)?),
            0x2e => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x2f => x2f_i32_load16_u(Parsable::parse(data, stack)?),
            0x30 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x31 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x32 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x33 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x34 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x35 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x36 => x36_i32_store(Parsable::parse(data, stack)?),
            0x37 => x37_i64_store(Parsable::parse(data, stack)?),
            0x38 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x39 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x3a => x3a_i32_store8(Parsable::parse(data, stack)?),
            0x3b => x3b_i32_store16(Parsable::parse(data, stack)?),
            0x3c => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x3d => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x3e => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x3f => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x40 => {
                let parse = u8::parse(data, stack)?;
                if 0x00 != parse {
                    Err(ParseError::Unknown0x40(Hex([parse])))?;
                }
                x40_grow
            }
            0x41 => x10_i32_const(i32::parse(data, stack)?),
            0x42 => x42_i64_const(Parsable::parse(data, stack)?),
            0x43 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x44 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x45 => x45_i32_eqz,
            0x46 => x46_i32_eq,
            0x47 => x47_i32_ne,
            0x48 => x48_lt_s,
            0x49 => x49_i32_lt_u,
            0x4a => x4a_i32_gt_s,
            0x4b => x4b_i32_gt_u,
            0x4c => x4c_i32_le_s,
            0x4d => x4d_i32_le_u,
            0x4e => x4e_i32_ge_s,
            0x4f => x4f_i32_ge_u,
            0x50 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x51 => x51_i64_eq,
            0x52 => x52_i64_ne,
            0x53 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x54 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x55 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x56 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x57 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x58 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x59 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x5a => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x5b => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x5c => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x5d => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x5e => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x5f => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x60 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x61 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x62 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x63 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x64 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x65 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x66 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x67 => x67_i32_clz,
            0x68 => x68_i32_ctz,
            0x69 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x6a => x6a_i32_add,
            0x6b => x6b_i32_sub,
            0x6c => x6c_i32_mul,
            0x6d => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x6e => x6e_i32_div_u,
            0x6f => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x70 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x71 => x71_i32_and,
            0x72 => x72_i32_or,
            0x73 => x73_i32_xor,
            0x74 => x74_i32_shl,
            0x75 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x76 => x76_i32_shr_u,
            0x77 => x77_i32_rotl,
            0x78 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x79 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x7a => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x7b => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x7c => x7c_i64_add,
            0x7d => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x7e => x7e_i64_mul,
            0x7f => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x80 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x81 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x82 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x83 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x84 => x84_i64_or,
            0x85 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x86 => x86_i64_shl,
            0x87 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x88 => x88_i64_shr_u,
            0x89 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x8a => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x8b => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x8c => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x8d => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x8e => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x8f => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x90 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x91 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x92 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x93 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x94 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x95 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x96 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x97 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x98 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x99 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x9a => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x9b => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x9c => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x9d => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x9e => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0x9f => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xa0 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xa1 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xa2 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xa3 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xa4 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xa5 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xa6 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xa7 => xa7_i32_wrap_i64,
            0xa8 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xa9 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xaa => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xab => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xac => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xad => xad_i64_extend_i32_u,
            0xae => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xaf => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xb0 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xb1 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xb2 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xb3 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xb4 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xb5 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xb6 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xb7 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xb8 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xb9 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xba => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xbb => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xbc => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xbd => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xbe => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xbf => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xc0 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xc1 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xc2 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xc3 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xc4 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xc5 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xc6 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xc7 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xc8 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xc9 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xca => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xcb => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xcc => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xcd => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xce => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xcf => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xd0 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xd1 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xd2 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xd3 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xd4 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xd5 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xd6 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xd7 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xd8 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xd9 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xda => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xdb => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xdc => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xdd => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xde => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xdf => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xe0 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xe1 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xe2 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xe3 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xe4 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xe5 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xe6 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xe7 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xe8 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xe9 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xea => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xeb => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xec => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xed => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xee => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xef => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xf0 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xf1 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xf2 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xf3 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xf4 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xf5 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xf6 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xf7 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xf8 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xf9 => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xfa => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xfb => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xfc => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xfd => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xfe => Err(ParseError::UnknownInstruction(Hex(typ)))?,
            0xff => Err(ParseError::UnknownInstruction(Hex(typ)))?,
        })
    }
}
